PUT http://localhost:8080/events/4
Content-Type: application/json
Authorization: YOUR_JWT_TOKEN_HERE

{
  "name": "Updated of my new event",
  "description": "Updated description",
  "location": "Updated locatikon",
  "date_time": "2025-01-01T13:37:00.000Z"
}